/**
  * @brief  Fills each USART_InitStruct member with its default value.
  * @param  USART_InitStruct: pointer to a USART_InitTypeDef structure which will
  *         be initialized.
  * @retval None
  */
  void USART_StructInit(USART_InitTypeDef* USART_InitStruct){
    /* USART_InitStruct members default value */
    USART_InitStruct->USART_BaudRate = 9600;
    USART_InitStruct->USART_WordLength = USART_WordLength_8b;
    USART_InitStruct->USART_StopBits = USART_StopBits_1;
    USART_InitStruct->USART_Parity = USART_Parity_No ;
    USART_InitStruct->USART_Mode = USART_Mode_Rx | USART_Mode_Tx;
    USART_InitStruct->USART_HardwareFlowControl = USART_HardwareFlowControl_None;  
  }
  
  // Generated by OpenAI GPT-4o
  void USART_StructInit(USART_InitTypeDef* USART_InitStruct) 
  {
      USART_InitStruct->BaudRate = 9600;
      USART_InitStruct->WordLength = USART_WordLength_8b;
      USART_InitStruct->StopBits = USART_StopBits_1;
      USART_InitStruct->Parity = USART_Parity_No;
      USART_InitStruct->Mode = USART_Mode_Rx | USART_Mode_Tx;
      USART_InitStruct->HwFlowCtl = USART_HwFlowCtl_None;
  }