def parsemsg(self, s):
    """
    Breaks a message from an IRC server into its prefix, command, and arguments.
    Theved from twisted
    """
    prefix = ''
    trailing = []
    if not s:
        #raise IRCBadMessage("Empty line.")
        return None, None, None
    if s[0] == ':':
        prefix, s = s[1:].split(' ', 1)
    if s.find(' :') != -1:
        s, trailing = s.split(' :', 1)
        args = s.split()
        args.append(trailing)
    else:
        args = s.split()
    command = args.pop(0)
    return prefix, command, args

# Generated by OpenAI GPT-4o
def parsemsg(self, s):
    prefix = ''
    trailing = []
    if not s:
        raise ValueError("Empty line.")
    if s[0] == ':':
        prefix, s = s[1:].split(' ', 1)
    if s.find(' :') != -1:
        s, trailing = s.split(' :', 1)
        args = s.split()
        args.append(trailing)
    else:
        args = s.split()
    command = args.pop(0)
    return prefix, command, args