/**
 * Copies the input stream to the output stream using the specified buffer size
 * @param in the input stream
 * @param out the output stream
 * @param bufferSize the buffer size to use when copying
 * @throws IOException
 */
public static void copy(InputStream in, OutputStream out, int bufferSize)
		throws IOException
{
	byte[] b = new byte[bufferSize];
	int read;

	while ((read = in.read(b)) != -1)
	{
		out.write(b, 0, read);
	}
}

// Generated by Amazon Q
public static void copy(InputStream in, OutputStream out, int bufferSize)
		throws IOException
{
	byte[] buffer = new byte[bufferSize];
	int read;
	while ((read = in.read(buffer)) != -1)
	{
		out.write(buffer, 0, read);
	}
}