/*
** function to be used with macro "fasttm": optimized for absence of
** tag methods
*/
const TValue *luaT_gettm (Table *events, TMS event, TString *ename){
    const TValue *tm = luaH_getstr(events, ename);
    lua_assert(event <= TM_EQ);
    if (ttisnil(tm)) {  /* no tag method? */
      events->flags |= cast_byte(1u<<event);  /* cache this fact */
      return NULL;
    }
    else return tm;
  }
  
// Generated by GitHub Copilot
const TValue *luaT_gettm (Table *events, TMS event, TString *ename) 
{
    const TValue *tm = luaH_getshortstr(events, ename);
    lua_assert(event <= TM_EQ);
    if (notm(tm)) {  /* no tag method? */
        events->flags |= cast_byte(1u << event);  /* cache this fact */
        return NULL;
    }
    else return tm;
}